# Commonly used Numpy Concepts in ML
Specifically in our pre-processing

### The @ operator for matrix multiplication
It is an alternative to np.matmul

In [1]:
import numpy as np

In [2]:
a = np.array([[1, 2],[3, 4]])
b = np.array([[5, 6],[7, 8]])

result = a @ b
print("Product of 2 matrices using @", result)

Product of 2 matrices using @ [[19 22]
 [43 50]]


## Array Broadcasting in NumPy

Ordinarily, to do math on two arrays, their shapes must match. Broadcasting solves this by automatically "stretching" or copying the smaller array behind the scenes so it matches the shape of the larger array.

* A standard 1D array like np.array([1, 2, 3]) is flat (shape (3,)).
* Adding [:, None] turns it into a column vector (shape (3, 1)).

In [3]:
row_offsets = np.array([10, 20, 30])
row_offsets.shape

(3,)

In [4]:
row_offsets[:, None].shape

(3, 1)

In [6]:
another_2d_array = np.array([[10], [20], [30]])
another_2d_array.shape

(3, 1)

So given a flat 1 dimensional array, 

* the \[:, None\] operator turns it into a dimensional array where every element becomes an array of size 1
* the n elements become n rows and 1 column

In [7]:
import numpy as np

# 1. Create a 3x3 matrix
matrix = np.array([[1, 1, 1],
                   [2, 2, 2],
                   [3, 3, 3]])

# 2. Create a 1D array of values to add to each row
row_offsets = np.array([10, 20, 30])

# 3. Use [:, None] to turn the 1D array into a column vector and add them
# Shape of matrix: (3, 3)
# Shape of row_offsets[:, None]: (3, 1)
result = matrix + row_offsets[:, None]

print("Result of Broadcasting:\n", result)

Result of Broadcasting:
 [[11 11 11]
 [22 22 22]
 [33 33 33]]


# Indirect Sorting (np.argsort)

* Sorting function returns the index permutations rather than sorting arrays directly
* In standard sorting, lose track of where those values originally lived.
* The Indirect Sorting becomes useful, when the data is represented as multiple logically related arrays
* You can apply the exact same index sequence to every parallel list or array.

In [10]:
file_values = np.array([15.45, 2.01, 10.8])
file_names = ["file1", "file2", "file3"]
sorted_indices = np.argsort(file_values)
print("sorted_indices: ", sorted_indices)
sorted_file_names = [file_names[index] for index in sorted_indices]
print("sorted_file_names: ", sorted_file_names)

sorted_indices:  [1 2 0]
sorted_file_names:  ['file2', 'file3', 'file1']


# Floating point Tolerances

* If you use a strict equality check (==) on floating-point numbers , valid data can fail simply because of a rounding discrepancy at the 15th decimal place.
* 0.1 + 0.2 does not equal 0.3 exactly; it equals 0.30000000000000004.
* np.allclose introduces a safety buffer using tolerances

In [14]:
first_array = np.array([0.5, 0.5])
second_array = np.array([0.50000001, 0.499999999])

print("Strict equality check: ", first_array == second_array)

# atol is absolute tolerance, rtol is relative tolerance
closeness = np.allclose(first_array, second_array, atol=1e-4, rtol=0)
print("Closeness check: ", closeness)

Strict equality check:  [False False]
Closeness check:  True


# Moore-Penrose Pseudoinverse (np.linalg.pinv)

* Linear regression uses least-squares to fit a line to points,
* while the matrix pseudoinverse uses least-squares to fit one coordinate system to another
* The Moore-Penrose tool is a robust way of doing this, it won't fail when the matrix has data that produces NaN/inf values or LinAlgErro

In [15]:
import numpy as np

# 1. Create a non-square matrix (3 rows, 2 columns)
# A standard inverse (np.linalg.inv) only works on square matrices and will throw a LinAlgError here.
A = np.array([[1, 2],
              [3, 4],
              [5, 6]], dtype=float)

b = np.array([1, 2, 3], dtype=float)

# 2. Compute the Moore-Penrose Pseudoinverse
pinv_A = np.linalg.pinv(A)

# 3. Find the least-squares best-fit solution
# You've got the inverse already, this is how we use the inverse
# so, solution is the best fitting vector such that A * solution = b
solution = pinv_A @ b

print("Pseudoinverse of A:\n", np.round(pinv_A, 4))
print("\nLeast-squares solution vector:", solution)

Pseudoinverse of A:
 [[-1.3333 -0.3333  0.6667]
 [ 1.0833  0.3333 -0.4167]]

Least-squares solution vector: [0.  0.5]


In [17]:
## Just for fun, invert the inverse to see if you are getting the value back.
print(np.linalg.pinv(pinv_A))
print("====================")
print(A @ solution)

[[1. 2.]
 [3. 4.]
 [5. 6.]]
[1. 2. 3.]
