In [2]:
!pip install torch


[notice] A new release of pip is available: 26.1 -> 26.2.1
[notice] To update, run: pip install --upgrade pip


## Simple demo of a custom pytorch dataset and dataloader

In [4]:
import torch
from torch.utils.data import Dataset, DataLoader

In [5]:
class SimpleDataSet(Dataset):
    """
    A toy data set that returns feature and label pair
    feature = [index]
    label = [index * 2]
    """
    def __init__(self, size:int = 10):
        self.size = size

    def __len__(self) -> int:
        # Required method
        # gives the size of the dataset to the dataloader
        return self.size

    def __getitem__(self, idx: int):

        if idx >= self.size or idx < 0:
            raise IndexError("invalid index", idx)

        # create fake data based on the idx
        # torch tensors expect iterables as inputs, features are generally floats
        feature = torch.tensor([float(idx)], dtype=torch.float32)
        label = torch.tensor([float(idx * 2)], dtype=torch.float32)

        return feature, label      
  
    
    

In [6]:
dataset = SimpleDataSet(5)

loader = DataLoader(dataset, batch_size=2, shuffle=True, num_workers=0)

for batch_x, batch_y in loader:
    print("label batch: ", batch_x.tolist())
    print("feature batch: ", batch_y.tolist())
    print("---")

label batch:  [[3.0], [0.0]]
feature batch:  [[6.0], [0.0]]
---
label batch:  [[1.0], [4.0]]
feature batch:  [[2.0], [8.0]]
---
label batch:  [[2.0]]
feature batch:  [[4.0]]
---


## Converting variable length arrays to tensors of uniform length

variable-length multi-series records being stacked into uniform, zero-padded tensors.

In [8]:
from torch.nn.utils.rnn import pad_sequence

In [9]:
records = [
    {
        "series_a": [1.0, 2.0, 3.0],
        "series_b": [10.0, 20.0]
    },
    {
        "series_a": [4.0, 5.0],
        "series_b": [30.0, 40.0, 50.0, 60.0]
    },     
    {
        "series_a": [7.0, 8.0, 9.0],
        "series_b": [70.0, 90.0]
    }, 
]

In [10]:
series_a_list = [torch.tensor(r["series_a"], dtype=torch.float32) for r in records]
series_b_list = [torch.tensor(r["series_b"], dtype=torch.float32) for r in records]

In [16]:
series_a_padded = pad_sequence(series_a_list, batch_first=True, padding_value=0.0)
series_b_padded = pad_sequence(series_b_list, batch_first=True, padding_value=0.0)

In [17]:
print("series a padded's shape", series_a_padded.shape)
print("series a padded :\n ", series_a_padded)

series a padded's shape torch.Size([3, 3])
series a padded :
  tensor([[1., 2., 3.],
        [4., 5., 0.],
        [7., 8., 9.]])


In [18]:
print("series b padded's shape", series_b_padded.shape)
print("series b padded :\n ", series_b_padded)

series b padded's shape torch.Size([3, 4])
series b padded :
  tensor([[10., 20.,  0.,  0.],
        [30., 40., 50., 60.],
        [70., 90.,  0.,  0.]])


#### *Note*: The main point of converting a list into a tensor is to move your data into the numerical format that PyTorch (and GPUs) are designed to work with efficiently

## Categorical Feature Encoding

#### Mapping string descriptors (like "TCP", "UDP") into integer feature vectors or one hot vectors suitable for a neural network

In [21]:
labels = ["ASIA","NA", "EUR", "AUS", "EUR", "ASIA", "SA", "AUS"]
zones = sorted(set(labels))
loc_to_id = {loc:idx for idx, loc in enumerate(zones)}
encoded_labels = [loc_to_id[label] for label in labels]

In [26]:
num_classes = len(zones)
# the below line creates a matrix of zeroes
one_hot_tensor = torch.zeros(len(encoded_labels), len(zones), dtype=torch.float32)
"""
This line uses advanced encoding - It is the same as
one_hot_tensor[0, encoded_labels[0]] = 1.0
one_hot_tensor[1, encoded_labels[1]] = 1.0
one_hot_tensor[2, encoded_labels[2]] = 1.0
...
one_hot_tensor[N-1, encoded_labels[N-1]] = 1.0
"""
one_hot_tensor[range(len(encoded_labels)), encoded_labels] = 1.0

In [27]:
print("one_hot_tensor shape:", one_hot_tensor.shape)
print("one_hot_tensor:\n", one_hot_tensor)

one_hot_tensor shape: torch.Size([8, 5])
one_hot_tensor:
 tensor([[1., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 1., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [1., 0., 0., 0., 0.],
        [0., 0., 0., 0., 1.],
        [0., 1., 0., 0., 0.]])


## How PyTorch is used in our MRI training and inference

PyTorch is the software framework that builds, trains, saves, and runs our neural networks. ResNet34 and the vision transformer used by DINOv2 are model architectures; PyTorch executes their operations. DINOv2 also names the pretraining method used to obtain the encoder's starting weights.

Think of the architecture as the program's structure, the weights as learned numerical parameters, and PyTorch as the engine that performs the calculations on the CPU or GPU.

| Stage | How we use PyTorch |
|---|---|
| Prepare inputs | Convert groups of MRI slices into tensors (multidimensional arrays) and move them to the GPU. |
| Build the model | Connect the image encoder, pooling operations, and classifier that produces twelve scores. Our ResNet backbone comes from torchvision. |
| Make predictions | Run the input tensors through the model using its current weights. This is the forward pass. |
| Calculate training loss | Compare the output scores with official binary labels or community soft labels using binary cross-entropy with logits. Our code masks missing labels. |
| Learn | Autograd computes gradients; the Adam optimizer uses them to update trainable weights. |
| Save and resume | Save model weights and training state in checkpoint files such as best.pt and last.pt. |
| Run inference | Load saved weights and predict without updating them or computing training gradients. |


### ResNet training: learning from labelled studies

```text
MRI slice triplets (three neighbouring slices used as channels)
    → Shared ResNet34 extracts features from each triplet
    → Mean/max pooling summarizes each series
    → Mean pooling combines series into a study representation
    → Classifier produces twelve logits
    → Masked loss compares logits with study-level labels
    → PyTorch computes gradients through the model
    → Adam updates the ResNet and classifier weights
```

A **feature** is a number in the model's learned representation of an image. A **logit** is a raw output score, before conversion to a probability. A **loss** is the numerical error signal used for training. A **gradient** describes how a small change to a parameter affects that loss; the optimizer uses gradients to choose updates.

Each MRI study has twelve targets. The labels describe the whole study, not individual slices. The same ResNet weights process every triplet: we do not train a separate CNN for each image.

Binary cross-entropy with logits accepts both binary targets (0 or 1) and soft targets (such as 0.2 or 0.85). It incorporates the sigmoid calculation internally, so we feed it raw logits. Unknown targets are excluded by a mask rather than treated as negative findings.


### Inference: using what the model has learned

```text
New MRI study
    → Read DICOM images and apply the saved preprocessing
    → Build MRI slice triplets
    → Run the same architecture with saved weights
    → Obtain twelve logits
    → Apply sigmoid once to obtain twelve probabilities
    → Write the study's predictions to submission.csv
```

Inference does not need labels and does not run an optimizer. It must reproduce the image preparation, target order, and aggregation expected by the trained model.

Two separate PyTorch controls matter:

- `model.eval()` changes the behaviour of layers such as dropout and BatchNorm for evaluation.
- `torch.no_grad()` or `torch.inference_mode()` disables gradient tracking, reducing memory and computation. Calling `eval()` alone does not disable gradients.

The model's weights stay fixed during inference. The predictions can change when the input images change, but the model does not learn from those images during the submission run.


### Our ResNet and DINOv2 training setups differ

| | ResNet34 pipeline | Frozen-DINOv2 pipeline |
|---|---|---|
| Image encoder | ResNet34 CNN initialized from ImageNet weights | Pretrained DINOv2 vision transformer |
| Encoder weights during training | Updated by training | Held fixed (frozen) |
| Image features | Recomputed during training because encoder weights change | Extracted once and cached, then reused for head training |
| Study prediction | Pooling and a classifier | Attention-based prediction heads |
| What learns? | The CNN and classifier; BatchNorm running statistics remain fixed in our implementation | Only the prediction heads |

Frozen means the encoder's parameters are not updated. It does not mean its outputs are identical for different images. At inference time, both pipelines use fixed exported weights; the DINOv2 encoder still has to extract features from new test images.

### Checkpoints and the surrounding tools

`best.pt` stores our best-validation checkpoint for export. `last.pt` stores the latest completed training state, including optimizer, scheduler, random states, training history, and the best checkpoint so far. Use `last.pt` to resume; the exported `model.pt` package is intended for inference. These filenames are conventions chosen by our code, not mandatory PyTorch names.

PyTorch does not handle the entire workflow:

- **pydicom and GDCM:** read and decode DICOM images.
- **NumPy and preprocessing code:** prepare numerical image arrays.
- **pandas:** read label tables and write submission CSVs.
- **scikit-learn:** calculate metrics such as AUROC.
- **Kaggle:** provides the notebook environment, GPU, attached inputs, and model hosting.

Selecting “PyTorch” when publishing a Kaggle Model describes its framework. Kaggle hosts the files; our inference code uses PyTorch to load and execute the model.
